### ISSUE TITLE
securityContext warnings on 4.11

### ISSUE THREAD

**Issue by jmontleon** [konveyor/crane-operator#55]
Editing any of our deployments complains about these not being set. We probably need to update the configs with these values or whatever is appropriate.
```
spec:
  template:
    spec:
      containers:
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```
