### ISSUE TITLE
Add example CatalogSource and instructions for usage

### ISSUE THREAD

**Issue by eriknelson** [konveyor/crane-operator#7]
Example CatalogSource:

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: mtk-operator
  namespace: openshift-marketplace
spec:
  image: 'quay.io/jgabani/mtk-operator-index:v99.0.0'
  sourceType: grpc
```

Also need a README for how to use this.
